sudo: false
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk7

before_install:
  # TODO: To release, setup git config and run `./mvnw -s ./.settings.xml release:prepare` locally.
  #       Once tag-driven automation is setup, these parameters will be used by travis.
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  # If we aren't a pull request, we are publishing either a snapshot or a release.
  #   We don't currently publish the benchmarks or interop modules, as they are test code only.
  - '[ "${TRAVIS_BRANCH}" = master ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw -s ./.settings.xml -Prelease deploy -nsu'
  # If we are on a pull request, don't build javadoc or source jars (release profile), and certainly don't deploy!
  #   We also add the MYSQL_USER so that these tests will be invoked.
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || MYSQL_USER=root ./mvnw install -nsu'

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /v^[0-9]/

env:
  global:
  - GIT_NAME="Spencer Gibb"
  - GIT_EMAIL=spencer@gibb.us
  # Ex. travis encrypt CI_DEPLOY_PASSWORD=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: VjjdX3tKOtVrrwqBkd0561csr7WtLU98KLIDhvZCn/b2wm2+DpTsW53hn4f0N8mnorTxTleN4SPswg3iLi3nFikk2uj9c/BRU8C7IH2PBhm3lLZmzSl4qgWaOIw+b1qhfkmmftXHTLDVesPO7Zke6q1PIDDBUYlOiIFdoF/LedbKL2jHux0nJxTk6vj8QvtpsOIHRRLGgtZNwo8cMFfq3V3CHhF2LP7P8jtF92sK5CSoYZRg9G9WYL7qSK+4N4Dol1sOTazpZf0iufYbdPL3IBVbOR9cW3JX0J41CAZCnpRjQMlD12he9vngEP4uWyuds9KJAdxdpmPeGrDf3YRC/do+LXQJ2Uiciw957DDuo8pc78iH3iUh5grScl/fw1RRw2X/9jqtirAhzm8nITGSy6vxSlZ27xEjGtwAOL6ppqzO4lzvb3QABxSNkQKBQJKiN/U8MlCGxItzuCmFVIfbIZbN7/mnc957zoIBfKq0coZYlpjt3XXeAWtuytHSOyo4TXfp74pDORzr0FVzAaPymfh2bnnreHt4w/K2EKLY7rRDWZ4eUyu7P3hYTQua29SGLxkr5hDznMIl35SDLZzr0WmjWYdsT2/3ljo4TauYMg9bHdqAEjkHQhbeqXiPd9yo9JCeK/GhlSoQAWtmeO23U0L/cC60RM6QnHP+o+X5/C8=
  # Ex. travis encrypt CI_DEPLOY_USERNAME=your_bintray_user --add
  - secure: i9Uh7d+v+LsDm9dzz99Cmj7f+Iv3YLumUOHmgTj3UIkg51So+GV+nJiR8Pq0egGNspVfmh0v5FLS7OhtH/mZAoVKrd3rIEkVaPSCxfdWphXA2f+9DX6SNOBoRUc/vrb9XiLeIZ1fiTa+G5aav+vsJcnvS4hYO5NRsc6g8QefTP1UNQgAEcHKPDhtYe+EISj/gVq1KTBuCAWkAJ7rCgWQcBfT8BGuM1e/RNeNycfyWFO/7vXK7M7lGcdggSbWY9YYDN20FcaHsvArNPoq23I53Wv4Hj917oeQF3+hPaK8vCq+qgNrYH4t9kgi2wdkKtYJk2TLSBPaT6lovhY+fUrVFNZkBGJEQuWUmgeCXhB7EhM7ZNFq0GGLMsKLWw8Y1DV+2OBYIeCSnXEOtzOaq12Nbp94BiLwdazMjCTXjQ4OLBTIFJiBCnNkiwiGfFIiRC+QXcKtapsgpv9z81h5fRzcazKGjAZjwXdePB5DsY6OtF4wbVkyPHYao6hXD/AyBqPQxnphvF3UvN11WTKGCL0vTh6KEJJmIu6YYMIuCq50QBYm8gzcbnlubsj7kbwMYgeqUUbLjchMXbkxv4jOUPHYqgaF+dSdY1b8ksggnc+00C4wvnYie68CaN8/OJHqDwbx2RRspioGrIitIbJjtB6wzvjB2NVaRjGyCDTAaWCsO5E=
